from deevek_world import (
    hello_boo,
)

hello_boo()

# pypi-AgENdGVzdC5weXBpLm9yZwIkMmFlODNlYTEtNDZkZS00YjFjLWEyYWQtYTYxODJkNmIzZDkxAAIqWzMsImE5Mzg5ZjQwLWE3NzYtNGZhZi05ZjE3LTAzZjI2MDgyMmM0MiJdAAAGIPPiyiH7DLR6mSvPrVCZsotmnD_YIJrsJ9k8o9UFpmVB